package com.weixf.spring;


import lombok.extern.slf4j.Slf4j;
import org.dom4j.Document;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;
import org.dom4j.io.OutputFormat;
import org.dom4j.io.XMLWriter;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import java.io.FileWriter;

@Slf4j
@SpringBootTest
public class PDMCreateTest {


    @Test
    public void test() throws Exception {
        // 创建一个新的Document对象
        Document document = DocumentHelper.createDocument();
        // 添加自定义处理指令
        // document.addProcessingInstruction("xml", "version='1.0' encoding='UTF-8'");
        document.addProcessingInstruction("PowerDesigner", "AppLocale=\"UTF16\" ID=\"{C1A3758A-C202-4059-BE77-555C74BF8F69}\" Label=\"\" LastModificationDate=\"1515748001\" Name=\"承保核心\" Objects=\"2477\" Symbols=\"93\" Target=\"ORACLE Version 11g\" Type=\"{CDE44E21-9669-11D1-9914-006097355D9B}\" signature=\"PDM_DATA_MODEL_XML\" version=\"15.1.0.2850\"");
        document.addComment("do not edit this file");

        // 添加根元素
        Element Model = document.addElement("Model");



        // 可以继续添加子元素等操作...

        // 设置输出格式
        OutputFormat format = OutputFormat.createPrettyPrint();
        format.setEncoding("UTF-8");

        // 写入文件
        XMLWriter writer = new XMLWriter(new FileWriter("output.xml"), format);
        writer.write(document);
        writer.close();

        System.out.println("XML file with custom declaration created successfully.");

    }

}
